# -*- coding: utf-8 -*-
"""code  projet Chatbot juridique avec RAG

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WO0l9sE-bZwZsWAInaNKHig9XdvoFEYo
"""
#lien vers data dans colab : https://drive.google.com/drive/folders/1W8V8cXS5Gby8H7SpKSzwhe_TmaqH50qC?usp=sharing
!pip install transformers sentence-transformers faiss-cpu PyPDF2 gradio

from google.colab import drive
drive.mount('/content/drive')

"""Étape 1 : Charger et extraire le texte des PDFs"""

from PyPDF2 import PdfReader

def extract_text(pdf_path):
    reader = PdfReader(pdf_path)
    text = ""
    for page in reader.pages:
        text += page.extract_text() + "\n"
    return text

# Exemple : mettre le chemin vers ton PDF
text = extract_text("/content/drive/MyDrive/projet nlp/Code du travail - Légifrance.pdf")
print(text[:500])  # affiche le début pour vérifier

"""Étape 2 : Découper le texte en chunks"""

def chunk_text(text, chunk_size=500, overlap=50):
    words = text.split()
    chunks = []
    for i in range(0, len(words), chunk_size - overlap):
        chunk = " ".join(words[i:i + chunk_size])
        chunks.append(chunk)
    return chunks

chunks = chunk_text(text)
print(f"Nombre de chunks : {len(chunks)}")
print(chunks[0])  # vérifier le premier chunk

"""ÉTAPE 3 : Embeddings + Index FAISS (le cœur du RAG)"""

!pip install sentence-transformers faiss-cpu

"""3.2 Charger le modèle d’embeddings

On utilise Sentence-BERT (très bon pour le RAG).
"""

from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

"""3.3 Calculer les embeddings des chunks"""

import numpy as np

embeddings = embedding_model.encode(
    chunks,
    show_progress_bar=True,
    convert_to_numpy=True
)

print("Shape des embeddings :", embeddings.shape)

"""3.4 Créer l’index FAISS

"""

import faiss

dimension = embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(embeddings)

print("Nombre de vecteurs dans l'index :", index.ntotal)

"""3.5 Test du retrieval (super important)"""

def retrieve_chunks(question, k=3):
    question_embedding = embedding_model.encode([question])
    distances, indices = index.search(question_embedding, k)
    return [chunks[i] for i in indices[0]]

question = "Quels sont les droits du salarié en cas de licenciement ?"
results = retrieve_chunks(question)

for i, res in enumerate(results):
    print(f"\n--- Passage {i+1} ---\n")
    print(res[:500])

"""ÉTAPE 4 : Génération de réponse avec LLM (RAG complet)

4.1 Installer le LLM
"""

!pip install transformers accelerate

"""4.2 Charger le modèle LLM

On prend un modèle léger mais efficace pour QA.
"""

from transformers import pipeline

llm = pipeline(
    "text-generation",
    model="mistralai/Mistral-7B-Instruct-v0.2",
    max_new_tokens=300,
    temperature=0.2
)

"""4.3 Construire le prompt RAG"""

def build_prompt(question, retrieved_chunks):
    context = "\n\n".join(retrieved_chunks)

    prompt = f"""
Tu es un assistant juridique spécialisé en droit du travail français.

Réponds uniquement à partir des extraits suivants.
Si la réponse n'est pas présente, dis clairement : "Je ne sais pas".

Extraits :
{context}

Question :
{question}

Réponse (avec citation des articles ou sources si possible) :
"""
    return prompt

"""4.4 Générer la réponse finale"""

prompt = build_prompt(question, results)

response = llm(prompt)[0]["generated_text"]

print(response)

"""ÉTAPE 5 : Interface Chatbot avec Gradio

5.1 Installer Gradio
"""

!pip install gradio transformers accelerate

"""5.2 Chargement du LLM"""

from transformers import pipeline

llm = pipeline(
    "text2text-generation",
    model="google/flan-t5-base",
    max_new_tokens=300
)

"""5.3 Prompt RAG"""

def build_prompt(question, retrieved_chunks):
    context = "\n\n".join(retrieved_chunks)
    return f"""
You are a legal assistant specialized ONLY in the French Labour Code (Code du travail).

Answer the question ONLY using the articles from the Code du travail provided below.
If the answer is not found in these articles, say exactly: Je ne sais pas.

Code du travail excerpts:
{context}

Question:
{question}

Answer (mention articles if possible):
"""

"""5.4 Fonction Chatbot"""

def chatbot(question):
    try:
        retrieved = retrieve_chunks(question, k=3)
        prompt = build_prompt(question, retrieved)
        result = llm(prompt)
        return result[0]["generated_text"]
    except Exception as e:
        return f"Erreur interne : {str(e)}"

"""5.5 Interface Gradio"""

import gradio as gr

interface = gr.Interface(
    fn=chatbot,
    inputs=gr.Textbox(lines=2, placeholder="Posez votre question en droit du travail..."),
    outputs=gr.Textbox(label="Réponse du chatbot"),
    title="🤖 Chatbot juridique – Droit du travail (RAG)",
    description="Ce chatbot répond à des questions juridiques simples à partir du Code du travail."
)

interface.launch(share=True, debug=True)